### ISSUE TITLE
No Snapcraft support on Apple Silicon

### ISSUE THREAD

**Issue by atmoio** [canonical/multipass#2399]
`multipass find` lists the following:

```
Image                       Aliases           Version          Description
18.04                       bionic            20220104         Ubuntu 18.04 LTS
20.04                       focal,lts         20220118         Ubuntu 20.04 LTS
21.04                       hirsute           20220118         Ubuntu 21.04
21.10                       impish            20220118         Ubuntu 21.10
anbox-cloud-appliance                         latest           Anbox Cloud Appliance
charm-dev                                     latest           A development and testing environment for charmers
minikube                                      latest           minikube is local Kubernetes
```

But I can't use any of them with snapcraft:

**snap/snapcraft.yml:**
`base: core18 `

```
$ snapcraft
Launching a VM.
Build environment is in unknown state, cleaning first.
info failed: The following errors occurred:
instance "snapcraft-my-snap-name" does not exist
launch failed: Unable to find an image matching "core18". Please use `multipass find` for supported remotes and images.
An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
```

Same result if I change `base` to `bionic`, `'18.04'`, or anything else. What am I missing? How do I get snapcraft:core18 image?

---

macOS 12.0.1, **arm64**
multipass   1.8.1+mac
multipassd  1.8.1+mac
snapcraft, version 5.0

**Comment by Saviq** [comment]
Hi @moughxyz, we currently don't have images to support Snapcraft natively on the M1.

A workaround is to use `remote-build` or launching a "builder" (`multipass launch -c8 -m8G -d40G -nbuilder`), set up LXD (`multipass exec builder -- sudo lxd init --auto`), mount your code ([`multipass mount …`](https://multipass.run/docs/mount-command)) and and use `snapcraft --use-lxd` inside.

Sorry for the hoops, we'll be working on streamlining this in the future.

**Comment by moughxyz** [comment]
Ah gotcha, thanks.

**Comment by moughxyz** [comment]
Btw, I had this all running fine on my M1 before I upgraded snapcraft and multipass. If I want to go back to a workable configuration where I can get back core18, would I downgrade snapcraft, multipass, or both?

**Comment by Saviq** [comment]
@moughxyz not really possible… Those images just don't exist for ARM64…

**Comment by moughxyz** [comment]
Right I was using the x64 images I believe. Would I just require the x64 version of snapcraft/multipass?

**Comment by Saviq** [comment]
@moughxyz you'd require the x64 version of your MacBook, too :D

We don't currently support cross-architecture instances (and Rosetta can't help here).

**Comment by moughxyz** [comment]
Lol I'm not following—I had this working just fine a few hours ago. But my M1 was bootstrapped from a backup of my x64 MacBook. But even on my M1 I had no issues building an x64 snap.

**Comment by Saviq** [comment]
@moughxyz o.O… I just can't see how… The CPU can't virtualize (different to emulation) a x86_64 machine… Just for the fun of it, I tried installing 1.7.2 which had no arm64 support, was all x86_64, and it expectedly failed starting the VM:

```plain
[2022-01-20T22:08:31.087] [error] [prompt-dolphin] hv_vm_create HV_ERROR (unspecified error)
```

Similarly, with 1.8.1, ran under `arch -x86_64`, both the hyperkit and qemu backends failed:
```plain
[2022-01-20T22:15:47.473] [error] [stirred-ostrich] hv_vm_create HV_ERROR (unspecified error)
[2022-01-20T22:16:38.034] [warning] [radiant-groundhog] qemu-system-x86_64: -accel hvf: Error: HV_ERROR
```

We would love to know how you achieved building x86 snaps on the M1…

**Comment by moughxyz** [comment]
Sorry, I meant amd64, not x64. I'm mixed up because our Windows builds were suffixed x64 and our Snap builds were suffixed amd64. So, to clarify, I've been building amd64 builds on my M1 Mac for a few months now.

**Comment by Saviq** [comment]
@moughxyz yes, the same architecture is often referred to by any of these strings… It doesn't help

If you have any logs from a build that worked, we'd love to see it. So far we've not had any evidence that this could work, and we have a lot to show that it doesn't…

**Comment by Saviq** [comment]
@moughxyz all in all, the only thing that comes to mind was that you used [`snapcraft remote-build`](https://snapcraft.io/docs/remote-build), which builds on [Launchpad](https://launchpad.net/) servers.

**Comment by moughxyz** [comment]
I'm honestly not sure how electron-builder goes about packaging snaps, but I tested `electron-builder --linux --x64 -c.linux.target=snap` just now and it builds the snap just fine, using all the latest versions of snapcraft/multipass.

However looking at the logs it doesn't appear to be spawning anything snapcraft/multipass related. It also builds fine with networking disabled on my device, so I don't think it's remote-build.

This appears to be the build script: https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/targets/snap.ts

**Comment by Saviq** [comment]
@moughxyz Ah! `electron-builder` just packages things together. It has a static runtime that it downloads (and caches) and bundles into a snap package. No Snapcraft _or_ Multipass involved.

Mystery solved!

**Comment by moughxyz** [comment]
Ahhh 😅😅

**Comment by moughxyz** [comment]
So with that said, could I then build arm64 builds via this same mechanism?

**Comment by Saviq** [comment]
@moughxyz arm64 you can build natively, since the M1 is a arm64 CPU… and yes, `electron-builder` will work cross architecture because it doesn't actually execute any code in the target architecture.

**Comment by moughxyz** [comment]
Hmm, well I suppose this is what brought us here in the first place. When running `electron-builder --linux --arm64 -c.linux.target=snap`, it starts to use Snapcraft, and brings up the original error "Unable to find an image matching "core18"

Perhaps a missing runtime? I'll probably have to take that up with them.

**Comment by Saviq** [comment]
Ah yes, they may be falling back to building through Snapcraft in this case.

**Comment by Saviq** [comment]
Hi @0xE282B0 for now you can launch a beefy instance, mount your code and use `snapcraft --use-lxd` inside it. We're working on getting those images up for native experience.

**Comment by matheushent** [comment]
last comment was basically three months ago. How is this going? Is there any release date scheduled for releasing the images?

**Comment by matheushent** [comment]
@townsend2010 thank you for the quick response mate.

**Comment by moughxyz** [comment]
Would you have any idea how to use remote-build with electron-builder? I'm currently having a hard time putting together arm64 snaps on x64 machines in GitHub CI environments for an Electron app. 

I get `snapcraft does not currently support building arm64 on amd64`, which is fair enough, but electron-builder as mentioned above uses static assets and doesn't need to actually "build", so not sure what the source of this error is.

**Comment by anpep** [comment]
@townsend2010 The issue you mention seems to have been fixed already. Is there any news on this issue? Thank you!

**Comment by townsend2010** [comment]
Hi @anpep,

The issue I mentioned is fixed for Jammy, but it needs to be SRU'd to Bionic and Focal in order to support building core18 and core20 based snaps respectively.  Until the SRU's are complete and these arm64-based images are built and released, we can't support it.

**Comment by DaveFlashNL** [comment]
any updates on this? trying to build a linux arm64 on apple silicon and it still fails today

**Comment by townsend2010** [comment]
Hey @DaveFlashNL,

The SRU's I mentioned before for Bionic and Focal have been accepted and released, but still waiting on the CPC Team to publish these artifacts for those series.  I will follow up with them for when they may have an ETA on when this will happen.

**Comment by DaveFlashNL** [comment]
ah ok. @townsend2010 because we have a deadline on a project, and I currently can't even test the amd64 linux binaries (which i can build through node with the electron builder on apple silicon), as linux, or at least ubuntu (in a vm), has no emulation support for x86_64/amd64 as far as i can see, unline windows on arm or macos on apple silicon.

**Comment by DaveFlashNL** [comment]
oh i actually could test, that is if snap images run on asahi linux, but asahi linux is currently broken on my machine bacause apple OS upgrades mess with the bootloader, but from their github, that should be fixable, tho I haven't had time yet to do so.

**Comment by townsend2010** [comment]
Hey @DaveFlashNL,

I'm a little confused.  Are you trying to **build** an arm64-based Snap or are you just trying to test if an arm64-based based snap works on arm64-based Ubuntu?

**Comment by DaveFlashNL** [comment]
@townsend2010 no, sorry got a bit confused there, i meant to say test amd64 on ashi, as i think the asahi distro for apple silicon HAS emulation support for x64. but I'd have to research that some more. of i can't test any arm64 yet as it won't let me build on apple silicon yet

**Comment by pprindeville** [comment]
> Hi @moughxyz, we currently don't have images to support Snapcraft natively on the M1.
> 
> A workaround is to use `remote-build` or launching a "builder" (`multipass launch -c8 -m8G -d40G -nbuilder`), set up LXD (`multipass exec builder -- sudo lxd init --auto`), mount your code ([`multipass mount …`](https://multipass.run/docs/mount-command)) and and use `snapcraft --use-lxd` inside.
> 
> Sorry for the hoops, we'll be working on streamlining this in the future.

Any closer to having M1 support? I do Linux development on an M1 MacBook Pro using UTM to run my jammy VM’s.

**Comment by pprindeville** [comment]
Is an M1/M2 binary different from an aarch64 binary in any way or are they instruction set compatible? Will the same binary run on a Graviton EC2 instance, for example?

**Comment by townsend2010** [comment]
@pprindeville,

I'm not sure I really follow what you are asking.  Do you mean if a snap built in an arm64 Multipass instance on M1/M2 will work on other arm64 based Linuxes?

**Comment by pprindeville** [comment]
That's right.

**Comment by townsend2010** [comment]
@pprindeville, yes any Snap package artifacts produced in the arm64 Multipass instance will be usable on any Linux distro that supports Snaps.  I hope this answers your question.  Thanks!

**Comment by DaveFlashNL** [comment]
any updates on this? this is starting to seriously affect my ability to develop applications properly on my arm64 machines running various arm versions of linux...

**Comment by townsend2010** [comment]
Hi @DaveFlashNL!

Yes, it has finally been fixed by the Public Cloud team and we have incorporated it into Multipass.  It is included in the upcoming 1.12 release and if you are willing to try a release candidate, you can get it here: https://github.com/canonical/multipass/releases/tag/v1.12.0-rc

Thanks!

**Comment by DaveFlashNL** [comment]
ah ok. no rush, so how soon will it be out of rv and fully released? @townsend2010

**Comment by townsend2010** [comment]
@DaveFlashNL, the RC is currently undergoing regression testing and if all goes well, I'm hoping it will be released next week after the macOS and Windows packages get properly signed.

**Comment by pprindeville** [comment]
Any news?

**Comment by townsend2010** [comment]
Hey @pprindeville, yep it was [released](https://github.com/canonical/multipass/releases/tag/v1.12.0) today!

**Comment by MrMYHuang** [comment]
multipass 1.12.0 works well with snapcraft (installed through homebrew) on Apple Silicon! I successfully built an arm64 snap on Apple Silicon and install it in a Ubuntu arm64 VM.

If anyone encounters an error `[Errno 1] Operation not permitted: snapcraft.yaml` during `snapcraft snap,` it can be fixed by allowing multipassd "Full Disk Access."
![image](https://github.com/canonical/multipass/assets/12458706/dc27835e-3048-4663-ac5a-49d74002b730)

**Comment by jacobsvante** [comment]
@MrMYHuang How did you get it to work? Can you show your `snapcraft.yaml`?

I'm still getting `craft_parts.errors.InvalidArchitecture: Architecture 'arm64' is not supported.`. Using multipass 1.12.0 and snapcraft 7.3.1, both latest installable via homebrew.

**Comment by MrMYHuang** [comment]
> @MrMYHuang How did you get it to work? Can you show your `snapcraft.yaml`?
> 
> I'm still getting `craft_parts.errors.InvalidArchitecture: Architecture 'arm64' is not supported.`. Using multipass 1.12.0 and snapcraft 7.3.1, both latest installable via homebrew.

I guess you use core18 in your snapcraft.yaml. I use core20 instead.
Run this command on Apple Silicon. It shows available snapcraft arm64 images. They don't contain core18.
```
% multipass find snapcraft:
Image                       Aliases           Version          Description
snapcraft:20.04             focal,core20      20230606         Ubuntu 20.04 LTS
snapcraft:22.04             jammy,lts,core22  20230606         Ubuntu 22.04 LTS
```

**Comment by jacobsvante** [comment]
I'm using `base: core22` which I'm assuming should mean that snapcraft will use the multipass image `snapcraft:22.04`.

Strangly enough, building works for me if I change to `base: core20`...?!

@MrMYHuang Have you successfully tried `base: core22`?

**Comment by townsend2010** [comment]
Hi @jacobsvante!

The `craft_parts.errors.InvalidArchitecture: Architecture 'arm64' is not supported` is an error coming from Snapcraft and is independent of Multipass.  I think you should follow up with them on https://forum.snacraft.io to figure out what may be wrong with your `snapcraft.yaml`.

Regarding `core18`, it's available, but is not shown anymore due to Bionic falling out of the 5 year support window.  If you do:
`% multipass find --show-unsupported snapcraft:`
it will indeed show `core18`.

**Comment by MrMYHuang** [comment]
> @MrMYHuang How did you get it to work? Can you show your `snapcraft.yaml`?

This is my snapcraft.yaml:
https://github.com/MrMYHuang/cbetar2/tree/master/snap

**Comment by jacobsvante** [comment]
> Hi @jacobsvante!
> 
> The `craft_parts.errors.InvalidArchitecture: Architecture 'arm64' is not supported` is an error coming from Snapcraft and is independent of Multipass. I think you should follow up with them on https://forum.snacraft.io to figure out what may be wrong with your `snapcraft.yaml` or even `snapcraft` itself.
> 
> Regarding `core18`, it's available, but is not shown anymore due to Bionic falling out of the 5 year support window. If you do: `% multipass find --show-unsupported snapcraft:` it will indeed show `core18`.

Thanks, I've now posted my issue here: https://forum.snapcraft.io/t/architecture-arm64-is-not-supported-error-on-apple-m1-with-core22-base/35634

**Comment by jacobsvante** [comment]
Thanks buddy 😀👍
