### ISSUE TITLE
[snap] GUI crashes when opening

### ISSUE THREAD

**Issue by Sploder12** [canonical/multipass#4253]
**Describe the bug**
When using the snap version of Multipass the GUI immediately exits ungracefully upon opening producing no error logs.

**To Reproduce**
1. Open the GUI
2. Observe crash (or hang)
3. Observe no errors in logs

**Expected behavior**
The GUI does not crash and it produces logs on why it crashed.

**Logs**
```
2025-07-16 05:36:00.048245 INFO Sent FindRequest{showImages: true, showBlueprints: false}
2025-07-16 05:36:00.241390 INFO Sent VersionRequest{}
2025-07-16 05:36:00.317063 INFO FindRequest{showImages: true, showBlueprints: false} received FindReply{showImages: true, imagesInfo: [{os: Ubuntu, release: Core 16, version: 20200818, aliasesInfo: [{alias: core}, {alias: core16}], codename: Core 16}, {os: Ubuntu, release: Core 18, version: 20211124, aliasesInfo: [{alias: core18}], codename: Core 18}, {os: Ubuntu, release: Core 20, version: 20230119, aliasesInfo: [{alias: core20}], codename: Core 20}, {os: Ubuntu, release: Core 22, version: 20230717, aliasesInfo: [{alias: core22}], codename: Core 22}, {os: Ubuntu, release: Core 24, version: 20240603, aliasesInfo: [{alias: core24}], codename: Core 24}, {os: Ubuntu, release: 22.04 LTS, version: 20250702, aliasesInfo: [{alias: 22.04}, {alias: j}, {alias: jammy}], codename: Jammy Jellyfish}, {os: Ubuntu, release: 24.04 LTS, version: 20250704, aliasesInfo: [{alias: 24.04}, {alias: n}, {alias: noble}, {alias: lts}, {alias: default}], codename: Noble Numbat}, {os: Ubuntu, release: 25.04, version: 20250701, aliasesInfo: [{alias: 25.04}, {alias: p}, {alias: plucky}], codename: Plucky Puffin}, {os: Ubuntu, release: 25.10, version: 20250705, aliasesInfo: [{remoteName: daily, alias: 25.10}, {remoteName: daily, alias: q}, {remoteName: daily, alias: questing}, {remoteName: daily, alias: devel}], codename: Questing Quokka}, {os: Ubuntu, release: AdGuard Home Appliance, version: 20200812, aliasesInfo: [{remoteName: appliance, alias: adguard-home}], codename: Core 18}, {os: Ubuntu, release: Mosquitto Appliance, version: 20200812, aliasesInfo: [{remoteName: appliance, alias: mosquitto}], codename: Core 18}, {os: Ubuntu, release: Nextcloud Appliance, version: 20200812, aliasesInfo: [{remoteName: appliance, alias: nextcloud}], codename: Core 18}, {os: Ubuntu, release: openHAB Home Appliance, version: 20200812, aliasesInfo: [{remoteName: appliance, alias: openhab}], codename: Core 18}, {os: Ubuntu, release: Plex Media Server Appliance, version: 20200812, aliasesInfo: [{remoteName: appliance, alias: plexmediaserver}], codename: Core 18}]}
2025-07-16 05:36:00.317255 INFO FindRequest{showImages: true, showBlueprints: false} is done
```

**Additional info**
- OS: Ubuntu 24.04
- CPU architecture: x86
- `multipass version`: 1.17.0-dev.123.pr4239+g82cbee96 (also present on other PRs)
- `multipass get local.driver`: qemu

**Additional context**
Only happens with the snap, luckily it doesn't effect 1.16.0

**Comment by ricab** [comment]
Hey @Sploder12, I just tried this in `--edge` and I could not reproduce. Could this be related to the certificate investigations you've been doing?

**Comment by Sploder12** [comment]
> Hey [@Sploder12](https://github.com/Sploder12), I just tried this in `--edge` and I could not reproduce. Could this be related to the certificate investigations you've been doing?

I'm unsure, if I do `--stable` then the GUI works but going to `--edge` right after breaks it. I do have external storage directory set up so maybe that's related?

**Comment by ricab** [comment]
I still couldn't reproduce:

```
$ snap info multipass | grep installed
installed:          1.17.0-dev.145+g878509cb            (15300) 89MB -
$ sudo grep -ao 'MULTIPASS_STORAGE=[a-z/]*' /proc/$(pgrep multipassd)/environ
MULTIPASS_STORAGE=/home/ricab/tmp/mpdata
$ ll /var/snap/multipass/common/data
total 8
drwxr-xr-x 2 root root 4096 jul 16 16:40 .
drwxr-xr-x 6 root root 4096 jul 16 16:39 ..
$ ll /var/snap/multipass/common/cache/
total 8
drwxr-xr-x 2 root root 4096 jul 16 16:40 .
drwxr-xr-x 6 root root 4096 jul 16 16:39 ..
```

Could this be related to that libffi stuff? Do you have something set in your environment?

**Comment by Sploder12** [comment]
I managed to get a run with interesting logs

```
Gtk-Message: 08:43:54.058: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(multipass_gui:13042): Gtk-WARNING **: 08:43:54.112: GTK+ module /snap/multipass/15300/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 08:43:54.113: Failed to load module "canberra-gtk-module"

(multipass_gui:13042): Gtk-WARNING **: 08:43:54.114: GTK+ module /snap/multipass/15300/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 08:43:54.114: Failed to load module "canberra-gtk-module"
2025-07-17 08:43:54.398919 DEBUG Got Screen{frame: Rect.fromLTRB(1920.0, 0.0, 3840.0, 1080.0), scaleFactor: 1.0, visibleFrame: Rect.fromLTRB(1920.0, 32.0, 3840.0, 1014.0)}
2025-07-17 08:43:54.399027 DEBUG Got last window size: null
2025-07-17 08:43:54.399050 DEBUG Computed default window size: Size(1400.0, 822.0)
2025-07-17 08:43:54.655822 INFO Sent FindRequest{showImages: true, showBlueprints: false}
2025-07-17 08:43:54.681718 INFO Sent VersionRequest{}
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
multipass_gui: ../../src/xcb_io.c:730: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

**Comment by xmkg** [comment]
I've managed to reproduce the problem too:

```
❯ multipass.gui 
Cannot load module /snap/multipass/15300/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: /snap/multipass/15300/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: undefined symbol: g_string_free_and_steal
/snap/multipass/15300/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so does not export GTK+ IM module API: /snap/multipass/15300/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: undefined symbol: g_string_free_and_steal
ERROR: /snap/multipass/15300/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 exited abnormally with status 1
ln: failed to create symbolic link '/home/mkg/snap/multipass/15300/.local/share/glib-2.0/schemas/org.gtk.Settings.ColorChooser.gschema.xml': File exists
ln: failed to create symbolic link '/home/mkg/snap/multipass/15300/.local/share/glib-2.0/schemas/org.gtk.Settings.Debug.gschema.xml': File exists
ln: failed to create symbolic link '/home/mkg/snap/multipass/15300/.local/share/glib-2.0/schemas/org.gtk.Settings.EmojiChooser.gschema.xml': File exists
ln: failed to create symbolic link '/home/mkg/snap/multipass/15300/.local/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml': File exists
/snap/multipass/15300/gnome-platform/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas: symbol lookup error: /snap/multipass/15300/gnome-platform/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas: undefined symbol: g_task_set_static_name
ERROR: compile_schemas /snap/multipass/15300/gnome-platform/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas exited abnormally with status 127
Gtk-Message: 13:36:03.890: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(multipass_gui:234866): Gtk-WARNING **: 13:36:03.923: GTK+ module /snap/multipass/15300/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 13:36:03.924: Failed to load module "canberra-gtk-module"

(multipass_gui:234866): Gtk-WARNING **: 13:36:03.924: GTK+ module /snap/multipass/15300/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 13:36:03.924: Failed to load module "canberra-gtk-module"
2025-07-18 13:36:04.225436 DEBUG Got Screen{frame: Rect.fromLTRB(0.0, 1080.0, 5120.0, 2520.0), scaleFactor: 1.0, visibleFrame: Rect.fromLTRB(0.0, 1110.0, 5120.0, 2520.0)}
2025-07-18 13:36:04.225502 DEBUG Got last window size: null
2025-07-18 13:36:04.225512 DEBUG Computed default window size: Size(1400.0, 822.0)
2025-07-18 13:36:04.298349 INFO Sent FindRequest{showImages: true, showBlueprints: false}
2025-07-18 13:36:04.312237 INFO Sent VersionRequest{}
2025-07-18 13:36:04.349854 INFO FindRequest{showImages: true, showBlueprints: false} received FindReply{showImages: true, imagesInfo: [{os: Ubuntu, release: Core 16, version: 20200818, aliasesInfo: [{alias: core}, {alias: core16}], codename: Core 16}, {os: Ubuntu, release: Core 18, version: 20211124, aliasesInfo: [{alias: core18}], codename: Core 18}, {os: Ubuntu, release: Core 20, version: 20230119, aliasesInfo: [{alias: core20}], codename: Core 20}, {os: Ubuntu, release: Core 22, version: 20230717, aliasesInfo: [{alias: core22}], codename: Core 22}, {os: Ubuntu, release: Core 24, version: 20240603, aliasesInfo: [{alias: core24}], codename: Core 24}, {os: Ubuntu, release: 22.04 LTS, version: 20250702, aliasesInfo: [{alias: 22.04}, {alias: j}, {alias: jammy}], codename: Jammy Jellyfish}, {os: Ubuntu, release: 24.04 LTS, version: 20250704, aliasesInfo: [{alias: 24.04}, {alias: n}, {alias: noble}, {alias: lts}, {alias: default}], codename: Noble Numbat}, {os: Ubuntu, release: 25.04, version: 20250701, aliasesInfo: [{alias: 25.04}, {alias: p}, {alias: plucky}], codename: Plucky Puffin}, {os: Ubuntu, release: 25.10, version: 20250705, aliasesInfo: [{remoteName: daily, alias: 25.10}, {remoteName: daily, alias: q}, {remoteName: daily, alias: questing}, {remoteName: daily, alias: devel}], codename: Questing Quokka}, {os: Ubuntu, release: AdGuard Home Appliance, version: 20200812, aliasesInfo: [{remoteName: appliance, alias: adguard-home}], codename: Core 18}, {os: Ubuntu, release: Mosquitto Appliance, version: 20200812, aliasesInfo: [{remoteName: appliance, alias: mosquitto}], codename: Core 18}, {os: Ubuntu, release: Nextcloud Appliance, version: 20200812, aliasesInfo: [{remoteName: appliance, alias: nextcloud}], codename: Core 18}, {os: Ubuntu, release: openHAB Home Appliance, version: 20200812, aliasesInfo: [{remoteName: appliance, alias: openhab}], codename: Core 18}, {os: Ubuntu, release: Plex Media Server Appliance, version: 20200812, aliasesInfo: [{remoteName: appliance, alias: plexmediaserver}], codename: Core 18}]}
2025-07-18 13:36:04.350028 INFO FindRequest{showImages: true, showBlueprints: false} is done
2025-07-18 13:36:04.350243 INFO VersionRequest{} received VersionReply{version: 1.17.0-dev.145+g878509cb, updateInfo: {}}
2025-07-18 13:36:04.350427 INFO VersionRequest{} is done
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
multipass_gui: ../../src/xcb_io.c:730: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)

```

It happens in the latest edge build, 24.04

**Comment by ricab** [comment]
OK, got it. Thanks both!

**Comment by tobe2098** [comment]
I have reproduced the error as well on accident (I could not do it before).

Logs indicate the same problem that I have found with Firmware Updater recently. The problem seemed to have been caused by moving my session to Wayland, and fixed by moving back to Xorg (although now it crashes for other unknown reasons). The log lines were identical before a core dumped:
```
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
```
To reproduce I snap installed first stable, then candidate and then edge, removing each snap without `remove --purge`, just `remove`.
After purging and re-installing, the multipass GUI behaves similarly to the freezing Firmware Updater, while other snaps are fine.
EDIT: The subsequent freeze is a problem on my graphics setup.

**Comment by chrisndbg** [comment]
@tobe2098 , @xmkg - can you still reproduce this issue from 2025?

**Comment by tobe2098** [comment]
No, and it is likely that it is already fixed by the flutter updates.

**Comment by chrisndbg** [comment]
@tobe2098 - Thanks. I'll close it then.
